installer: Build from git without 'non-free-firmware'
Allow the installer to be built without the non-free-firmware section.

Example command line:
lb config --distribution sid --debian-installer live
--debian-installer-distribution git --firmware-binary false
--firmware-chroot false

diff --git a/scripts/build/installer_debian-installer b/scripts/build/installer_debian-installer
--- a/scripts/build/installer_debian-installer
+++ b/scripts/build/installer_debian-installer
@@ -344,7 +344,8 @@ export LINUX_KERNEL_ABI=\$(dpkg-query --showformat "\\\${db:Status-Abbrev} \\\${
 export EXTRAFILES=""
 if [ "${LB_ARCHITECTURE}" = "amd64" ]
 then
-	apt-get --yes install firmware-sof-signed firmware-intel-sound
+	# Don't fail if these packages are not found
+	apt-get --yes install firmware-sof-signed firmware-intel-sound || true
 	for file in \$(dpkg-query -L firmware-sof-signed;dpkg-query -L firmware-intel-sound;dpkg-query -L linux-image-\${LINUX_KERNEL_ABI}-amd64|egrep "/(drm|i915|drm_display_helper|drm_buddy|cec|rc-core)\.ko"); do if [ -f \${file} ]; then EXTRAFILES="\${EXTRAFILES} \${file}"; fi; done
 	for file in \$(dpkg-query -L firmware-sof-signed;dpkg-query -L firmware-intel-sound;dpkg-query -L linux-image-\${LINUX_KERNEL_ABI}-amd64|egrep "/(drm|i915|drm_display_helper|drm_buddy|cec|rc-core)\.ko"); do if [ -L \${file} ]; then EXTRAFILES="\${EXTRAFILES} \${file}"; fi; done
 fi
